
services:
###> doctrine/doctrine-bundle ###
  database:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-root}"
      MYSQL_DATABASE: ${MYSQL_DATABASE:-test}
      MYSQL_USER: "${MYSQL_USER:-user}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD:-password}"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
###< symfony/mailer ###

  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html/

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html/
    ports:
      - "${NGINX_PORT:-80}:80"

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: database
      PMA_USER: "${MYSQL_USER:-user}"
      PMA_PASSWORD: "${MYSQL_PASSWORD:-password}"
    ports:
      - "${PHPMYADMIN_PORT:-3306}:80"
    depends_on:
      - database

volumes:
  db_data:
